#
# To connect from adminer: specify service name (mysql) rather than the container's IP address (localhost)
# To connect from mysql client: mysql -u root -h 127.0.0.1 -p
#
version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql.test
    container_name: mysql.test
    environment:
      MYSQL_ROOT_PASSWORD: s3c4Et
      MYSQL_USER: test
      MYSQL_PASSWORD: changeMe
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/sakila.sql:/docker-entrypoint-initdb.d/sakila.sql"

  adminer:
    image: adminer
    hostname: adminer.test
    container_name: adminer.test
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  localstack:
    image: localstack/localstack
    hostname: localstack.test
    container_name: localstack.test
    environment:
      - LOCALSTACK_DEBUG=0
      - LOCALSTACK_DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_PERSISTENCE=0
    ports:
      - "4566:4566"
    volumes:
      - "./docker/localstack/create_s3_bucket.sh:/docker-entrypoint-initaws.d/create_s3_bucket.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
